### ISSUE TITLE
Feedback for python - Attach and Detach a Block Device to a Virtual_Guest

### ISSUE THREAD

**Issue by chiberm** [softlayer/softlayer.github.io#85]
Feedback regarding: https://softlayer.github.io/python/attach_disk/
This does not work.
client['SoftLayer_Virtual_Guest'].attachDiskImage(5047903,id=15825861)
Traceback (most recent call last):
  File "C:\Home\CLOUD\eclipse\dropins\plugins\org.python.pydev_3.9.2.201502050007\pysrc\pydevd_comm.py", line 1081, in doIt
    result = pydevd_vars.evaluateExpression(self.thread_id, self.frame_id, self.expression, self.doExec)
  File "C:\Home\CLOUD\eclipse\dropins\plugins\org.python.pydev_3.9.2.201502050007\pysrc\pydevd_vars.py", line 344, in evaluateExpression
    result = eval(compiled, updated_globals, frame.f_locals)
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\softlayer-2.2.0-py2.7.egg\SoftLayer\API.py", line 510, in call_handler
    return self(name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\softlayer-2.2.0-py2.7.egg\SoftLayer\API.py", line 481, in call
    return self.client.call(self.name, name, *args, **kwargs)
  File "C:\Python27\lib\site-packages\softlayer-2.2.0-py2.7.egg\SoftLayer\API.py", line 344, in call
    verbose=self.verbose)
  File "C:\Python27\lib\site-packages\softlayer-2.2.0-py2.7.egg\SoftLayer\transport.py", line 65, in make_xml_rpc_api_call
    e.faultCode, e.faultString)
SoftLayerAPIError: SoftLayerAPIError(SOAP-ENV:Server): Internal Error

**Comment by chiberm** [comment]
So then, i tried this..
def attachDisk(detailsFilePath):
    id=15825861
    client = SoftLayer.API.Client('SoftLayer_Virtual_Guest', id=id, username=getUser(detailsFilePath), api_key=getKey(detailsFilePath))

    
    params=''' {
        "id": [
            '''+str(5047903)+'''
        ]
    }'''
    client.attachDiskImage(params)

--------------------------------------------portable Storage List retrieved---------------
 {'typeId': 241, 'modifyDate': '2016-05-07T14:16:35-05:00', 'description': 'test portable storage', 'storageRepository': {'typeId': 181, 'publicFlag': 0, 'description': '2x3-portable-storage-d6f53909-7c43-46e1-a7d2-344a9b4af9e5', 'datacenter': {'statusId': 2, 'id': 449612, 'name': 'syd01', 'longName': 'Sydney 1'}, 'id': 5047903, 'name': '2x3-portable-storage-d6f53909-7c43-46e1-a7d2-344a9b4af9e5'}, 'createDate': '2016-05-07T14:16:16-05:00', 'uuid': '7999f724-a876-4ac6-b284-6f400317c100', 'parentId': '', 'units': 'GB', 'capacity': 200, 'storageRepositoryId': 5047903, 'id': 15532859, 'name': 'test portable storage'}]

**Comment by chiberm** [comment]
This fails with SoftLayerAPIError: SoftLayerAPIError(SoftLayer_Exception_Public): You must provide a valid portable storage volume id.

**Comment by allmightyspiff** [comment]
I've updated the example to hopefully make it a bit more clear how it works.
